#  Copyright (c) 2024, RTE (https://www.rte-france.com)
#  See AUTHORS.txt
#  SPDX-License-Identifier: MPL-2.0
#  This file is part of BERTrend.

WARNING_ICON = ":material/warning:"
ERROR_ICON = ":material/error:"
INFO_ICON = ":material/info:"
EDIT_ICON = ":material/edit:"
ADD_ICON = ":material/add_circle:"
DELETE_ICON = ":material/delete:"
SUCCESS_ICON = ":material/check:"
SETTINGS_ICON = ":material/settings:"
TOPIC_ICON = ":material/speaker_notes:"
TREND_ICON = ":material/trending_up:"
MODELS_ICON = ":material/network_intelligence:"
EMBEDDING_ICON = ":material/memory:"
SAVE_ICON = ":material/save:"
TOPIC_EXPLORATION_ICON = ":material/explore:"
TOPIC_VISUALIZATION_ICON = ":material/monitoring:"
TEMPORAL_VISUALIZATION_ICON = ":material/timelapse:"
NEWSLETTER_ICON = ":material/newspaper:"
ANALYSIS_ICON = ":material/query_stats:"
DATA_LOADING_ICON = ":material/drive_folder_upload:"
MODEL_TRAINING_ICON = ":material/cognition:"
SERVER_STORAGE_ICON = ":material/database:"
CLIENT_STORAGE_ICON = ":material/upload:"
UNHAPPY_ICON = ":material/sentiment_extremely_dissatisfied:"
TOGGLE_ON_ICON = ":material/toggle_on:"
TOGGLE_OFF_ICON = ":material/toggle_off:"
NOISE_ICON = ":material/signal_cellular_off:"
WEAK_SIGNAL_ICON = ":material/signal_cellular_1_bar:"
STRONG_SIGNAL_ICON = ":material/signal_cellular_3_bar:"
DOWNLOAD_ICON = ":material/download:"
EMAIL_ICON = ":material/mail:"
RESTART_ICON = ":material/restart_alt:"

JSON_ICON = "🧾"
PARQUET_ICON = "📦️"
CSV_ICON = "📉"
XLSX_ICON = "📊"
